// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9eveMW0pLALjyFpiU_z7U8DYg04OGUMc',
    appId: '1:944828255989:web:4e72340f48797b998fbfbc',
    messagingSenderId: '944828255989',
    projectId: 'raahigo-10f32',
    authDomain: 'raahigo-10f32.firebaseapp.com',
    storageBucket: 'raahigo-10f32.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJvetDem5FPko2I4Pnei6Ug92C-qe9RSI',
    appId: '1:944828255989:android:d8ddd58e260fbf8a8fbfbc',
    messagingSenderId: '944828255989',
    projectId: 'raahigo-10f32',
    storageBucket: 'raahigo-10f32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUVSbbWYaxfoFBfNL6Ld0-LSGVouaIXlw',
    appId: '1:944828255989:ios:b1fcb3ac77f854428fbfbc',
    messagingSenderId: '944828255989',
    projectId: 'raahigo-10f32',
    storageBucket: 'raahigo-10f32.firebasestorage.app',
    iosBundleId: 'com.example.raahigo.raahigo',
  );
}
